version: '3.8'

services:
  phobos:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - phobosback-llm
    entrypoint: >
      bash -c "apt-get update && apt-get install -y netcat && \
      while ! nc -z phobosback-llm 8000; do sleep 1; done && \
      python app.py"
    runtime: nvidia
    devices:
      - "/dev/nvidia*:/dev/nvidia*"

  phobosback-llm:
    build: ../phobosback-llm
    ports:
      - "8000:8000"
    runtime: nvidia
    devices:
      - "/dev/nvidia*:/dev/nvidia*"
