name: Build and Deploy

on:
  push:
    branches: [ main ]  # You can change "main" to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # You can choose a different runner

    steps:
      - uses: actions/checkout@v3  # Checks out your code from GitHub
      - name: Login to Docker Hub (optional)  # Only if pushing to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker-compose build  # Uses docker-compose.yml to build image

      # Additional steps (optional)
      - name: Push Docker image to Docker Hub (optional)
        run: docker push <your_username>/<your_image_name>

      - name: Deploy to Hugging Face Spaces
        # Specific steps for deployment to Hugging Face Spaces will depend on their platform
        # Refer to Hugging Face documentation for details on deployment steps

