name: Build and Deploy

on:
  push:
    branches: [ main ]  # You can change "main" to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # You can choose a different runner

    steps:
      - uses: actions/checkout@v3  # Checks out your code from GitHub
      - name: Login to Docker Hub (optional)  # Only if pushing to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Remove this line (if using access token)
          password: ${{ secrets.DOCKER_PASSWORD }}  # Remove this line (if using access token)
          token: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build Docker image
        run: docker-compose build  # Uses docker-compose.yml to build image

      # Start services in the background
      - name: Start services
        run: docker-compose up -d

      - name: Get Docker Username from Secret
        run: echo "USERNAME=$(echo ${{ secrets.DOCKER_USERNAME }})" >> $GITHUB_ENV

      # Additional steps (optional)
      - name: Push phobos image to Docker Hub (optional)
        run: docker push $DOCKER_USERNAME/phobos:latest

      # Install Hugging Face CLI (only needed for deployment to Hugging Face Spaces)
      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      # Deploy to Hugging Face Spaces
      - name: Deploy to Hugging Face Spaces
        run: hf spaces upload $DOCKER_USERNAME/phobos:latest --env production
